[FEAT/#15] data 및 domain layer 구현(Firestore 연동 1/4)
boostcampwm-2024/and05-MAPISODE pull request #33
Opened 2024-11-14 11:27 UTC by Ameri-Kano

- in progress #15

## *📍 Work Description*

- data:episode 모듈 구현
  - repository 구현: DB와의 연결 후 작업 로직 작성
- domain:episode 모듈 구현
  - repository 및 DTO 선언

## *📢 To Reviewers*
> 말씀드렸듯이 DB에서 직접 데이터를 주고받은 비즈니스 로직 부분이 상당히 러프합니다. 정확하게 말하면 PR 이라기 보다는 코드리뷰 요청이 될 것 같습니다!

> 추가적으로, 이외의 user, group 등등도 구현부는 다르겠지만 모듈 구조는 동일하게 가게 될 것 같습니다. 개발 방향성에 대한 의견도 환영합니다!

## ⏲️Time
    - 3(의미없이 삽질한 +6시간 정도 포함...)

2024-11-14 12:19 UTC, haeti-dev requested changes
고생하셨습니다 리뷰 확인 부탁드려요~

2024-11-14 12:19 UTC, haeti-dev commented on app/src/main/kotlin/com/boostcamp/mapisode/MapisodeApplication.kt
> +		FirebaseApp.initializeApp(this)
함수화하는 것에 대해 우찌 생각하시나요?

2024-11-14 12:19 UTC, haeti-dev commented on build.gradle.kts
> +	id("com.google.gms.google-services") version "4.4.2" apply false
버전 카탈로그 방식을 사용해서 위 코드들과 컨밴션을 맞춰주세요

2024-11-14 12:19 UTC, haeti-dev commented on core/firebase/src/main/java/com/boostcamp/mapisode/firebase/firestore/FirestoreReference.kt
> +		fun database(): FirebaseFirestore = Firebase.firestore
👍

2024-11-14 12:19 UTC, taeheeL commented on data/episode/build.gradle.kts
> +	implementation(libs.firebase.firestore)
모든 data 모듈에 해당 의존성이 들어간다면, MapisodeDataPlugin에 넣어주심 될 것 같습니다

2024-11-14 12:19 UTC, taeheeL commented on data/episode/src/main/java/com/boostcamp/mapisode/episode/EpisodeRepositoryImpl.kt
> +			)
이런 group 같은 것을 상수나 enum class로 관리하는 것은 어떤가요?

2024-11-14 12:19 UTC, taeheeL commented on data/episode/src/main/java/com/boostcamp/mapisode/episode/EpisodeRepositoryImpl.kt
> +		}
얼리리턴은 좋습니다 👍 근데 나중에 실사용할때는 팀버를 제거하고 에러 처리 로직으로 바꿔야 할 것 같아요

2024-11-14 12:19 UTC, taeheeL commented on data/episode/src/main/java/com/boostcamp/mapisode/episode/EpisodeRepositoryImpl.kt
> +	): List<EpisodeDTO> {
아직 사용이 확정된 메서드는 아니지만 그래도 개선 사항을 말씀드리자면, Pair를 사용하는 것보다 data class를 사용하는 게 나을 것 같아요. naver map에 LatLng이란게 있는데 이거 쓰셔도 되고 별도로 만드셔도 될 것 같아요. 아마 따로 만들고 매핑하는 로직이 들어가는게 좋아보입니다. 매퍼 함수도 분리하는 식으로 SRP를 지켜주면 좋을 것 같아요~

2024-11-14 12:19 UTC, taeheeL commented on data/episode/src/main/java/com/boostcamp/mapisode/episode/EpisodeRepositoryImpl.kt
> +			.whereLessThanOrEqualTo("location", GeoPoint(end.first, end.second))
오호 이런식으로 범위를 줄여가는군요.. 
근데 Sequence 흐름을 따라가게는 못할까요? 나중에 다량의 데이터를 처리하려면 Collection으로 하면 메모리나 속도 측면에서 Sequence보다 퍼포먼스가 아쉬울 것 같습니다.

2024-11-14 12:19 UTC, taeheeL commented on data/episode/src/main/java/com/boostcamp/mapisode/episode/EpisodeRepositoryImpl.kt
> +		val newEpisodeId = UUID.randomUUID().toString().replace("-", "")
이렇게 생성한 ID가 기존에 DB에 있는 id와 중복되지 않을거란 보장이 현재 존재하나요?

2024-11-14 12:19 UTC, taeheeL commented on data/episode/src/main/java/com/boostcamp/mapisode/episode/EpisodeRepositoryImpl.kt
> +	private fun QuerySnapshot.toDTOList(): List<EpisodeDTO> {
DTO는 Dto라고 쓰는 게 맞습니다. Kotlin Naming Convention을 준수해주세요! 전체적으로 사용한 DTO를 전부 Dto로 바꿔주시면 좋을 것 같습니다~

2024-11-14 12:19 UTC, taeheeL commented on data/episode/src/main/java/com/boostcamp/mapisode/episode/di/RepositoryModule.kt
> +	@Binds
Q) Provides가 아니라 Binds를 사용한 이유가 있나요?

2024-11-14 12:19 UTC, taeheeL commented on domain/episode/src/main/java/com/boostcamp/mapisode/episode/EpisodeDTO.kt
> +data class EpisodeDTO(
Dto가 왜 Domain 레이어에 존재하나요?

2024-11-14 12:19 UTC, taeheeL commented on domain/episode/.gitignore
> +/build
이 파일은 삭제하셔도 됩니다. 루트 gitignore에서 다 지정해주고 있어서 불필요해요~

2024-11-14 12:19 UTC, taeheeL commented on data/episode/src/main/java/com/boostcamp/mapisode/episode/model/DTOtoModel.kt
> +internal fun EpisodeDTO.toFirestoreModel(database: FirebaseFirestore): EpisodeFirestoreModel =
EpisodeFirestoreModel는 어디에 쓰일 예정인가요?

2024-11-14 12:19 UTC, taeheeL commented on data/episode/src/main/java/com/boostcamp/mapisode/episode/model/EpisodeFirestoreModel.kt
> +	fun toDTO(id: String): EpisodeDTO = EpisodeDTO(
여기도 네이밍 수정해주세요.

2024-11-14 12:19 UTC, taeheeL commented on data/episode/src/main/java/com/boostcamp/mapisode/episode/model/EpisodeFirestoreModel.kt
> +		location = requireNotNull(location?.let { Pair(it.latitude, it.longitude) }),
Pair 보다는 data class 사용을 권해드립니다

2024-11-14 12:27 UTC, Ameri-Kano commented on app/src/main/kotlin/com/boostcamp/mapisode/MapisodeApplication.kt
> +		FirebaseApp.initializeApp(this)
코드가 한 줄 이어서 할까말까 하다가 그냥 작성했는데, 필요하다면 initFirebase() 로 작성해보면 될 것 같네요!

2024-11-14 12:28 UTC, Ameri-Kano commented on data/episode/src/main/java/com/boostcamp/mapisode/episode/EpisodeRepositoryImpl.kt
> +			)
사실 core:firebase 의 FirestoreConstants 에 정의되어 있긴 한데, 위치가 좀 맘에 들지 않아서 data 레이어로 옮겨오면 좋을 것 같습니다!

2024-11-14 12:29 UTC, Ameri-Kano commented on data/episode/src/main/java/com/boostcamp/mapisode/episode/EpisodeRepositoryImpl.kt
> +	): List<EpisodeDTO> {
매퍼 함수를 분리한다는 게 따로 데이터 클래스를 만드는 경우를 말씀하시는 게 맞을까요?

2024-11-14 12:34 UTC, Ameri-Kano commented on data/episode/src/main/java/com/boostcamp/mapisode/episode/EpisodeRepositoryImpl.kt
> +			.whereLessThanOrEqualTo("location", GeoPoint(end.first, end.second))
정확하게 말씀드리면 현재 코드는 하나하나씩 줄여간다기 보다는 쿼리 빌더라고 보는 게 맞습니다! 그래서 저 쿼리들을 모아서 한 번에 실행해주고, 보시는 것 처럼 등호(EqualTo) 와 부등호(GreaterThanOr...) 를 And 로 조합하는 경우에는 Firestore 에서 인덱싱을 해 줘야 하더라구요! 자체적으로 인덱싱 처리를 지원하기 때문에 속도에 있어 큰 문제가 일어나진 않을 것 같습니다!
> 등호 연산자와 부등호 연산자(<, <=, >, !=)를 결합하려면 [복합 색인](https://firebase.google.com/docs/firestore/query-data/indexing?authuser=1&hl=ko)을 만들어야 합니다.

[참고 자료](https://firebase.google.com/docs/firestore/query-data/queries?hl=ko#compound_and_queries)
시퀀스를 사용하는 방법은 한번 조사해 볼게요!

2024-11-14 12:36 UTC, Ameri-Kano commented on data/episode/src/main/java/com/boostcamp/mapisode/episode/EpisodeRepositoryImpl.kt
> +		val newEpisodeId = UUID.randomUUID().toString().replace("-", "")
UUID의 전체 경우의 수는 340,282,366,920,938,463,463,374,607,431,768,211,456개 라고 합니다! 아마... 온 세상 지구인이 우리 어플리케이션을 사용하더라도 중복될 확률은 굉장히 희박할 것 같습니다.

2024-11-14 12:38 UTC, Ameri-Kano commented on data/episode/src/main/java/com/boostcamp/mapisode/episode/di/RepositoryModule.kt
> +	@Binds
사실 잘 모르고 써서 조사해 봤습니다... 객체를 생성해줘야 하므로 Provides 를 사용하는 것이 적절하겠네요!

2024-11-14 12:39 UTC, Ameri-Kano commented on domain/episode/src/main/java/com/boostcamp/mapisode/episode/EpisodeDTO.kt
> +data class EpisodeDTO(
사용자의 입력을 받아서 Domain 레이어에서 DTO 로 변환하여 처리한다고 생각했습니다!

2024-11-14 12:40 UTC, Ameri-Kano commented on data/episode/src/main/java/com/boostcamp/mapisode/episode/model/DTOtoModel.kt
> +internal fun EpisodeDTO.toFirestoreModel(database: FirebaseFirestore): EpisodeFirestoreModel =
Firestore 데이터베이스의 Value Object 라고 생각하시면 될 것 같습니다!

2024-11-14 15:38 UTC, taeheeL commented on data/episode/src/main/java/com/boostcamp/mapisode/episode/EpisodeRepositoryImpl.kt
> +	): List<EpisodeDTO> {
네네 지금 Naver Map의 LatLng를 홈에서 사용하고 있는데, 제가 동역님이 만든 클래스를 쓰던지 아니면 매핑해서 쓰던지 해야될 것 같아요

2024-11-14 15:39 UTC, taeheeL commented on data/episode/src/main/java/com/boostcamp/mapisode/episode/EpisodeRepositoryImpl.kt
> +		val newEpisodeId = UUID.randomUUID().toString().replace("-", "")
ㅋㅋㅋ 그래도 나중에 기술적 도전으로 삼을 수는 있을 것 같네요 제가 무지했습니다..!

2024-11-14 15:41 UTC, taeheeL commented on data/episode/src/main/java/com/boostcamp/mapisode/episode/di/RepositoryModule.kt
> +	@Binds
그냥 질문이였습니다 ㅋㅋㅋ 지금은 Binds가 더 적합한데 이유를 나중에 찾아서 기록해주시면 좋을 것 같아요

2024-11-14 15:42 UTC, taeheeL commented on domain/episode/src/main/java/com/boostcamp/mapisode/episode/EpisodeDTO.kt
> +data class EpisodeDTO(
클린 아키텍처 원칙 상 Dto는 Data 레이어에 들어가야 됩니다. Domain에서 이러한 엔티티를 사용할 것이라면 Dto라는 네이밍을 쓰면 안될 것 같아요

2024-11-16 05:44 UTC, TaewoongR approved these changes
re-request 하실거라 생각하고 전 approve로 해놓겠습니다.
re-request 후에 코드리뷰 하려고 했는데, 두번 하는것도 좋겠다 해서 리뷰 남깁니다😎

2024-11-16 05:44 UTC, TaewoongR commented on app/build.gradle.kts
> +	id("com.google.gms.google-services")
리마인드용으로 코멘트 답니다!

2024-11-16 05:44 UTC, TaewoongR commented on .github/workflows/pr_checker.yml
> +
yml 파일 수정 저도 나중에 경험하고 싶네요

2024-11-16 05:44 UTC, TaewoongR commented on data/episode/src/main/java/com/boostcamp/mapisode/episode/di/DataModule.kt
> +}
힐트 Module 정의까지 하셨구나...이것까지 공부하고 적용하는데 시간 은근 걸렸을 것 같아요

2024-11-16 05:44 UTC, TaewoongR commented on data/episode/src/main/java/com/boostcamp/mapisode/episode/model/EpisodeFirestoreModel.kt
> +) {
Model 정의 좋습니다. 이것도 고민하시는데 시간 꽤 걸렸겠어요!

2024-11-18 06:56 UTC, Ameri-Kano commented on app/build.gradle.kts
> +	id("com.google.gms.google-services")
[8da8231](https://github.com/boostcampwm-2024/and05-MAPISODE/pull/33/commits/8da82310d7e0b1badfe6de7652d181cbf642860e) 커밋에서 수정 완료했습니다!

2024-11-18 06:56 UTC, Ameri-Kano commented on data/episode/src/main/java/com/boostcamp/mapisode/episode/di/DataModule.kt
> +}
선 적용 후 학습! 좀 더 학습해 봐야 할 부분입니다...

2024-11-18 08:44 UTC, shinythinking approved these changes
수고 많으셨습니다!!
LGTM

2024-11-18 08:55 UTC, taeheeL approved these changes

2024-11-18 09:04 UTC, TaewoongR approved these changes
수정 잘 봤습니다!!

2024-11-18 10:38 UTC, closed without merging