[FEAT/#75] login / firebase authentication 도입
boostcampwm-2024/and05-MAPISODE pull request #80
Opened 2024-11-20 15:13 UTC by shinythinking

- closed #75 

## *📍 Work Description*

- firebase authentication 관련 의존성 추가
- firebase authentication 도입하여 구글 소셜 로그인 구현
- 멀티 모듈 정리
- ui에 반영

## *📸 Screenshot*
(<img src="https://github.com/user-attachments/assets/6d24abe7-321c-42c4-979a-9139719dc309" width=270 />)

## *📢 To Reviewers*
- firebase authentication을 이용해서 구글 소셜 로그인을 구현했습니다.
- 처음 해보는 작업인지라 많은 우여곡절을 겪었습니다.
  - firebase 공식문서에는 xml 코드만 있다!!
  - 있는 코드도 Deprecate된 함수들을 사용한다...
  - 안드로이드 공식 문서에 해답이 있었다. 다만 사용법만 있어서 멀티모듈로 변환하는 작업이 필요했다.
  - hilt관련 문제로 5시간은 씨름한 것 같다. -> app 모듈에 의존성을 추가하여 해결!

## ⏲️Time

    - 12 h +

2024-11-20 15:35 UTC, Ameri-Kano approved these changes
고생 많으셨습니다! 굉장히 소중한 경험이라고 생각해서, 꼭 문서로 남겨두었으면 좋겠습니다.

2024-11-20 15:35 UTC, Ameri-Kano commented on app/build.gradle.kts
> +	implementation(libs.androidx.credential)
이쪽을 auth 관련 bundles 로 묶는 것도 좋아 보입니다.

2024-11-20 15:35 UTC, Ameri-Kano commented on data/auth/src/main/AndroidManifest.xml
> +</manifest>
필요없다면 삭제해도 좋을 것 같네요!

2024-11-20 15:35 UTC, Ameri-Kano commented on data/auth/src/main/java/com/boostcamp/mapisode/auth/AuthRepositoryImpl.kt
> +	}
callbackFlow 는 일반적인 flow 와 어떤 차이가 있는 건가요?

2024-11-20 15:35 UTC, Ameri-Kano commented on feature/login/src/main/java/com/boostcamp/mapisode/login/AuthViewModel.kt
> +}
MVI가 적용된 것 같지는 않네요! 그랬다면 시간이 너무 많이 걸렸겠죠?

2024-11-20 15:39 UTC, shinythinking commented on feature/login/src/main/java/com/boostcamp/mapisode/login/AuthViewModel.kt
> +}
네 ㅠㅠ 우선 익숙한 걸로 구현했습니다. 추후에 MVI 적용할 생각입니다!

2024-11-20 15:40 UTC, shinythink commented on data/auth/src/main/AndroidManifest.xml
> +</manifest>
commit에 넣지 않으려고 했는데 들어갔네요. 나중 Commit에서 삭제하겠습니다.

2024-11-20 15:40 UTC, shinythinking commented on app/build.gradle.kts
> +	implementation(libs.androidx.credential)
좋은 의견 감사합니다!!

2024-11-20 16:11 UTC, shinythinking commented on data/auth/src/main/java/com/boostcamp/mapisode/auth/AuthRepositoryImpl.kt
> +	}
Firebase나 Google Auth 같은 콜백 기반 API를 Flow로 변환할 때 사용할 수 있습니다!
* trySend()로 데이터 방출하고
* awaitClose()로 리소스 정리합니다.

2024-11-20 17:02 UTC, taeheeL requested changes
고생하셨습니다 리뷰 확인 부탁드려요~
모듈 간의 결합도를 낮추는 게 중요한 것 같아서, login 모듈 관련해서는 수정이 필요할 것 같습니다.

2024-11-20 17:02 UTC, haeti-dev commented on data/auth/src/main/java/com/boostcamp/mapisode/auth/AuthRepositoryImpl.kt
> +) : AuthRepository {
q) 구현체의 코드를 직접 삽입 안하고 인터페이스를 사용한 이유가 있나요? 인터페이스를 꼭 분리했어야 했나요?

2024-11-20 17:02 UTC, haeti-dev commented on domain/auth/src/main/java/com/boostcamp/mapisode/auth/User.kt
> +data class User(val id: String, val displayName: String?)
core:model에 있어도 되지 않을까요? 옮기면 나중에 presentation 레이어에서 편하게 사용할 수 있을 듯 합니다.

2024-11-20 17:02 UTC, haeti-dev commented on app/build.gradle.kts
> +	implementation(projects.feature.main)
이 모듈들이 app 모듈에 추가되어야 하는 이유는 뭔가요?

2024-11-20 23:05 UTC, shinythinking commented on domain/auth/src/main/java/com/boostcamp/mapisode/auth/User.kt
> +data class User(val id: String, val displayName: String?)
동의합니다! 옮기도록 하겠습니다!

2024-11-20 23:16 UTC, shinythinking commented on data/auth/src/main/java/com/boostcamp/mapisode/auth/AuthRepositoryImpl.kt
> +) : AuthRepository {
다른 로그인이 추가될 가능성을 염두에 두었습니다. 이렇게 하면 다른 소셜 로그인과 관련된 코드를 짜고 기존 코드를 확장만 하면 되기 때문입니다.

2024-11-20 23:34 UTC, shinythinking commented on app/build.gradle.kts
> +	implementation(projects.feature.main)
전이 의존성 때문에 data:auth만 추가해도 동작은 합니다. 다만 의존 관계를 명확히 보여주고자 다 추가했습니다. 다만, 다른 의존성들이 여기에 추가될 것을 생각하면 data:auth만 추가해도 괜찮을 것 같습니다. 어떻게 하는 게 좋을까요? 의견이 궁금합니다!
ps) 좀 더 공부를 해야할 것 같습니다 ㅠ

2024-11-21 00:59 UTC, TaewoongR reviewed
data, domain 모듈을 사용하지 않고 feature:login 에서 전부 정의하면 어떨까란 의견입니다.

2024-11-21 00:59 UTC, TaewoongR commented on data/auth/src/main/java/com/boostcamp/mapisode/auth/GoogleAuthDataSourceImpl.kt
> +			else -> throw RuntimeException("Invalid credential")
어제 이 부분에 대해서 문제가 있었음을 확인했습니다. 
사인님은 알고 계시겠지만, API 35 기기에서는 실행이 되지만 API 33 기기에서는 로그인 화면 창이 나타나지 않습니다.
<img src="https://github.com/user-attachments/assets/bc18d403-80df-4f32-b50c-3fcb9ac34610" width=800>
이를 해결하기 위해 ActivityContext를 주입하려 했지만, 진행하면서 되돌아보니 domain, data 모듈에서는 생명주기를 알고 있어야 하는가? 의 질문에 ui layer 외에는 의존하면 안된다 라는 결론을 세우고 리팩토링 과정을 중단했습니다.

또한, ActivityContext를 주입을 할 수 없었던 이유는 domain 모듈은 android 의존성이 없기 때문에 Activity 주기를 모릅니다.
그래서 data 모듈의 di module에서 스코프를 지정하는 과정에서 ActivityComponent로 설정할 때 domain 모듈에게 주입하는 과정에서 오류가 발생했습니다.

현재 제 생각은 이 로직 전부가 data 모듈이 아닌 feature:login 모듈에 존재하면 안될까 라는 의견을 갖고 있습니다.

2024-11-21 01:06 UTC, taeheeL commented on data/auth/src/main/java/com/boostcamp/mapisode/auth/AuthRepositoryImpl.kt
> +) : AuthRepository {
그 답변도 설득력 있긴 하지만, 사실 테스트 관련 답변을 기대했습니다 ㅎ

2024-11-21 01:07 UTC, taeheeL commented on app/build.gradle.kts
> +	implementation(projects.feature.main)
의존 관계를 명확히 보여주고자 다 추가했다는게 좀 말이 안되네요..? 당연히 필요한 것만 의존해야됩니다. 순환 의존성이 발생할 확률을 줄여주세요. 또 빌드 시간에 대한 이점을 가지는 멀티모듈 구조를 잘 활용하기 위해서는 줄여야 합니다

2024-11-21 11:15 UTC, closed without merging